spring:
  cloud:
    stream:
      default-binder: integration
      consumer:
        max-attempts: 1
      source:
        test
      function:
        definition: parking;testFunction

logging:
  level:
    ke.co.dynamodigital: trace