spring:
  cloud:
    stream:
      default-binder: integration
      consumer:
        max-attempts: 1
      function:
        definition: parking;testFunction
      #================================================================================================================#
      bindings:
        parking-in-0:
          destination: pawa.parking.exchange
          group: commons.parking.queue
      #================================================================================================================#
      rabbit:
        bindings:
          parkingConsumer-in-0:
            consumer:
              bindingRoutingKey: commons.parking.queue.binding
              delayedExchange: true
              autoBindDlq: true
              dlqTtl: 5000
              dlqDeadLetterExchange:
