spring:
  cloud:
    stream:
      default:
        contentType: application/json
        consumer:
          max-attempts: 1
        destination: pawa.parking.exchange
      bindings:
      #================================================================================================================#
      parkingSinkInput:
        destination:
        group: pawa.parking.queue
      parkingSourceOutput:
        destination:
      #================================================================================================================#
      rabbit:
        binding:
          parkingSinkInput:
            consumer:
              bindingRoutingKey: pawa.parking.queue.binding
              delayedExchange: true
              exchangeType: direct
          parkingSourceOutput:
            producer:
              routingKeyExpression: '''pawa.parking.queue.binding'''
              delayedExchange: true
              exchangeType: direct    
